### ISSUE TITLE
Duvida: Tem alguma maneira de deixar salvo as configurações?

### ISSUE THREAD

**Issue by gstavomota** [Dpbm/dreambooth-tutorial#10]
Gostaria  de saber se tem algum jeito de deixar salvo as configurações ou se toda vez que for usar tem que refazer aqueles passos todos dnv

**Comment by AlexJRC** [comment]
Tem sim, faz uma copia para o seu colab, e todas as alterações no codigo que você fizer, ficaram salvas lá

![image](https://user-images.githubusercontent.com/73409467/205413716-4d1a6fdf-b935-43df-a85e-85959f8ba570.png)

**Comment by gstavomota** [comment]
Mas aquele esquema de ter que esperar instalar as dependências  ainda tem que acontecer né? 

![image](https://user-images.githubusercontent.com/61586814/205450737-21bbada0-c258-419a-b2f4-e6ff20f56c09.png)

tipo esse xformers que demora mt

**Comment by Dpbm** [comment]
Por ser executado em uma máquina na nuvem fornecida pela Google, infelizmente é necessário fazer todos os passos todas as vezes que você quiser usar o algoritmo. 
No entanto, acredito que o problema do xformers seja temporário, uma vez que a versão pré compilada provavelmente será atualizada e tudo será mais rápido para executar.

Uma solução imediata para isso seria utilizar em seu computador local. Se você tiver um computador um mais potente, com uma placa Nvidia, basta instalar o `python` e o `jupyter notebook`, baixar o arquivo para sua máquina e rodar como no tutorial.  

---
Edit: como apontado pelo @yurirosas os requisitos são um tanto altos, se estiver interessado dê uma olhada no repositório oficial [aqui](https://github.com/huggingface/diffusers/tree/main/examples/dreambooth)

**Comment by yurirosas** [comment]
Para treinar próprias imagens no dreambooth não precisa ter 16gb de vram na GPU? Tornando inviável 99% das pessoas usarem suas próprias máquinas? 

Aqui o xformers não tá dando erro, mas o "accelerate launch train_dreambooth.py \" tá levevando 21min pra terminar.

**Comment by Dpbm** [comment]
> Para treinar próprias imagens no dreambooth não precisa ter 16gb de vram na GPU? Tornando inviável 99% das pessoas usarem suas próprias máquinas?
> 
> Aqui o xformers não tá dando erro, mas o "accelerate launch train_dreambooth.py " tá levevando 21min pra terminar.

Acredito que isso vai depender muito de vários fatores, como temperatura do local, quais outros processos estão rodando na máquina, o sistema operacional que está sendo usado, entre outros. 

Mas pensando nos requisitos mostrados no repositório, teoricamente é possível utilizar por volta de `8Gb de VRAM`, contudo isso `vai demandar um pouco mais` de `CPU` e `RAM`, se quiser mais detalhes veja [aqui](https://github.com/huggingface/diffusers/tree/main/examples/dreambooth#training-on-a-8-gb-gpu). 

Sendo assim, pensando no contexto brasileiro, é difícil para a maioria das pessoas conseguir uma máquina suficiente para isso, uma outra alternativa que poderia ser pensada é utilizar máquinas em cloud, como da `AWS`, `Azure`, `GCP`, etc., que teoricamente poderia sair mais barato e entregar uma potência suficiente.

Contudo, reconheço, fui infeliz ao dizer `um pouco mais potente`, obrigado pelo apontamento.
