### ISSUE TITLE
Dúvida: Passo 11 

### ISSUE THREAD

**Issue by anantunes54** [Dpbm/dreambooth-tutorial#11]
![image](https://user-images.githubusercontent.com/119764523/205464882-39365639-7e7a-40b9-a899-02b681efd649.png)
 No passo 11 está dando essa mensangem, de que OUTPUT_DIR não está definido. 

Não achei a solução no fórum.

NameError                                 Traceback (most recent call last)
[<ipython-input-12-169bc3808ed1>](https://localhost:8080/#) in <module>
      4 import matplotlib.image as mpimg
      5 
----> 6 weights_folder = OUTPUT_DIR
      7 folders = sorted([f for f in os.listdir(weights_folder) if f != "0"], key=lambda x: int(x))
      8 

NameError: name 'OUTPUT_DIR' is not defined

**Comment by EriveltonLima** [comment]
Você rodou todos os blocos anteriores?

**Comment by EriveltonLima** [comment]
@anantunes54  output dir é estabelecida no "Settings and run" no caso usamos no tutorial do dpbm no passo 10
como " stable_diffusion_weights/zwx "

**Comment by anantunes54** [comment]
> Você rodou todos os blocos anteriores?

Não rodei o "Upload your images by running this cell." porque eu subi as imagens direto na pasta. Tentei ajusar o output dir na etapa que você indicou mas mudou o problema, agora diz:  

FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-20-169bc3808ed1>](https://localhost:8080/#) in <module>
      5 
      6 weights_folder = OUTPUT_DIR
----> 7 folders = sorted([f for f in os.listdir(weights_folder) if f != "0"], key=lambda x: int(x))
      8 
      9 row = len(folders)

FileNotFoundError: [Errno 2] No such file or directory: '/content/" stable_diffusion_weights/zwx "'

**Comment by EriveltonLima** [comment]
é preciso que rode tbm o novo di_output 
![image](https://user-images.githubusercontent.com/364834/205467353-6841010d-a99b-4fb0-b882-031066e4857e.png)
