### ISSUE TITLE
Aceitar os termos no huggingface

### ISSUE THREAD

**Issue by BernardBibas** [Dpbm/dreambooth-tutorial#12]
Olá, não sou muito avançado, mas não consegui localizar como aceitar os termos do huggingface, vi na comunidade bastante gente tendo o mesmo tipo de problema e nenhuma solução clara.

**Comment by Dpbm** [comment]
Dei uma olhada no site, e realmente, eles removeram o botão de aceitar os termos, pode ser que agora não seja mais necessário aceitar, tente continuar o tutorial pulando essa parte. 
Caso algum erro aconteça durante o processo, volte com mais issue 😉
