### ISSUE TITLE
Erro : The following values were not passed to `accelerate launch` and had defaults used instead

### ISSUE THREAD

**Issue by Yoha-S** [Dpbm/dreambooth-tutorial#13]
Ontem tudo funcionou corretamente, mas hoje comecei a ter esse problema : 
![image](https://user-images.githubusercontent.com/120058073/206297055-c6f4b0e6-1706-45b2-8493-b3d658aa1020.png)

Inclusive ate peguei o colab pro pra ver se resolvia, mas não adiantou.

Alguma sugestão?

**Comment by lorenabuzzi** [comment]
Tenta trocando o xformers 
%pip install "git+https://github.com/facebookresearch/xformers@1d31a3a#egg=xformers"

**Comment by carloshqaraujo** [comment]
no meu quando tento trocar o sformers ele fica carregando eternamente e não acontece nada 
![erro](https://user-images.githubusercontent.com/105328936/206315975-0db4a935-b8d5-4812-a6c9-9352e09e4183.PNG)

**Comment by lorenabuzzi** [comment]
É normal levar  40 minutos ~ 1 hora
