### ISSUE TITLE
Inference error

### ISSUE THREAD

**Issue by rodrigopill** [Dpbm/dreambooth-tutorial#14]
Pra mim está aparecendo assim:

![image](https://user-images.githubusercontent.com/5111986/206298250-acd131fc-c6f0-419b-9ff4-a1872850411a.png)

Pastinha ok, não marquei o Google Drive.

Alguma ideia do que esteja ocorrendo?

**Comment by Rodrigonobrex** [comment]
Meu também  tá dando  erro e não apareceu o número Cinco  pra aceitar  o convite,  que raiva.

**Comment by LeonardoRJR** [comment]
![erro](https://user-images.githubusercontent.com/119907085/206343672-349db287-2c82-4200-9621-65e85a7b3d4b.png)
o meu está dando o mesmo erro, Alguém descobriu como que resolve?

**Comment by Dpbm** [comment]
No caso do @LeonardoRJR esse problema pode ter acontecido devido ao nome adicionado na token adicionado aqui:
```python
concepts_list = [

     {
         "instance_prompt":      "{NOME_DA_SUA_TOKEN_AQUI}",
         "class_prompt":         "photo of a person",
         "instance_data_dir":    "/content/data/{NOME_DA_SUA_TOKEN_AQUI}",
         "class_data_dir":       "/content/data/person"
     }
]

import json
import os
for c in concepts_list:
    os.makedirs(c["instance_data_dir"], exist_ok=True)

with open("concepts_list.json", "w") as f:
    json.dump(concepts_list, f, indent=4)
```

certifique se de tirar as chaves ("{" e "}") do `{NOME_DA_SUA_TOKEN_AQUI}`.

Remova as chaves dali, vá em `Runtime > Manage Sessions > Terminate` e rode tudo novamente

**Comment by Dpbm** [comment]
Nos casos do @Rodrigonobrex e do @rodrigopill, não sei ao certo, mas aconselho verificarem as seguintes coisas:

1. verifique se o `nome da token` foi inserido corretamente no script e se ele não possui nenhum caractere especial (como espaços, '.', ',', etc.)
2. verifique o mesmo [dessa resposta](https://github.com/Dpbm/dreambooth-tutorial/issues/14#issuecomment-1342623027)
3. verifique se essa pasta existe `stable_diffusion_weights/zwx/800` e se dentro dela há um arquivo `model_index.json`. Se houver outra pasta com esse arquivo `model_index.json` dentro, mude o `model_path` para o caminho dessa outra pasta:
 
![image](https://user-images.githubusercontent.com/75098594/206442787-10430898-0e6d-42ea-bdbf-a8d59d0e41eb.png)

Por fim, ao testar isso tudo,  vá em `Runtime > Manage Sessions > Terminate` e rode tudo novamente.

**Comment by LeonardoRJR** [comment]
> Nos casos do @Rodrigonobrex e do @rodrigopill, não sei ao certo, mas aconselho verificarem as seguintes coisas:
> 
> 1. verifique se o `nome da token` foi inserido corretamente no script e se ele não possui nenhum caractere especial (como espaços, '.', ',', etc.)
> 2. verifique o mesmo [dessa resposta](https://github.com/Dpbm/dreambooth-tutorial/issues/14#issuecomment-1342623027)
> 3. verifique se essa pasta existe `stable_diffusion_weights/zwx/800` e se dentro dela há um arquivo `model_index.json`. Se houver outra pasta com esse arquivo `model_index.json` dentro, mude o `model_path` para o caminho dessa outra pasta:
> 
> ![image](https://user-images.githubusercontent.com/75098594/206442787-10430898-0e6d-42ea-bdbf-a8d59d0e41eb.png)
> 
> Por fim, ao testar isso tudo, vá em `Runtime > Manage Sessions > Terminate` e rode tudo novamente.

Bom dia, então o problema que não está criando essa pasta 800 e nem esse arquivo no meu.
Sabe alguma solução?

**Comment by daciowinchester** [comment]
Vai em ISSUE na aba closed procura por Run to generate a grid of preview images from the last saved weights. https://github.com/Dpbm/dreambooth-tutorial/issues/15 olha o tutorial do cara la resolveu meu problema

**Comment by Filipinas09** [comment]
O @Dpbm valeu kk era uma coisa tão simples que resolveu tudo até criei essa conta só pra agradecer kkkjk o engraçado é que 2 dias atrás eu fiz com as chaves e der certo

**Comment by rodrigopill** [comment]
> Nos casos do @Rodrigonobrex e do @rodrigopill, não sei ao certo, mas aconselho verificarem as seguintes coisas:
> 
> 1. verifique se o `nome da token` foi inserido corretamente no script e se ele não possui nenhum caractere especial (como espaços, '.', ',', etc.)
> 2. verifique o mesmo [dessa resposta](https://github.com/Dpbm/dreambooth-tutorial/issues/14#issuecomment-1342623027)
> 3. verifique se essa pasta existe `stable_diffusion_weights/zwx/800` e se dentro dela há um arquivo `model_index.json`. Se houver outra pasta com esse arquivo `model_index.json` dentro, mude o `model_path` para o caminho dessa outra pasta:
> 
> ![image](https://user-images.githubusercontent.com/75098594/206442787-10430898-0e6d-42ea-bdbf-a8d59d0e41eb.png)
> 
> Por fim, ao testar isso tudo, vá em `Runtime > Manage Sessions > Terminate` e rode tudo novamente.

Obrigado pelo empenho. No meu caso, as pastas abaixo de "stable_diffusion_weights" não estavam sendo criadas. Hoje fiz do zero, como ontem e funcionou perfeitamente.

**Comment by Dpbm** [comment]
Vlw @rodrigopill e @Filipinas09 ❤️😊
