### ISSUE TITLE
Run to generate a grid of preview images from the last saved weights.

### ISSUE THREAD

**Issue by carloshqaraujo** [Dpbm/dreambooth-tutorial#15]
Boa noite! 
Eu estava usando o programa tranquilamente, mas hoje tentei rodar e apareceu esse erro, vi em um forum pra mudar o 
%pip install "git+https://github.com/facebookresearch/xformers@4c06c79#egg=xformers"
Mas quando colo o comando e coloco pra rodar ele fica carregando eternamente e nada acontece, deixei rodando mais de uma hora e simplesmente não funcionou. 
Alguém sabe o que pode ser?
![erro](https://user-images.githubusercontent.com/105328936/206317537-fc20526c-0257-4bc0-b5d2-555605525ecc.PNG)

**Comment by daciowinchester** [comment]
Conseguiu meen?

**Comment by carloshqaraujo** [comment]
> Conseguiu meen?

consegui sim, o segredo é rodar o %pip install "git+https://github.com/facebookresearch/xformers@4c06c79#egg=xformers"
aí vc reinicia e espera terminar, demora mais de uma hora mas depois funciona, e se alguma parte der erro é só rodar de novo

**Comment by daciowinchester** [comment]
Obrigado men, realmente funcionou!!
