### ISSUE TITLE
[ERRO] Run to generate a grid of preview images from the last saved weights.

### ISSUE THREAD

**Issue by CamilaGoulart** [Dpbm/dreambooth-tutorial#16]
Olá pessoal, boa noite, tudo bem?
Estou com bastante dificuldade pois já tentei diversas vezes e sempre acabo empacada nesse erro.
Alguém sabe o que pode ser e como resolver?

![erro Run generate](https://user-images.githubusercontent.com/112297674/206317894-710a254c-b898-4069-b1a7-3a356d8b77b5.jpg)

**Comment by lorenabuzzi** [comment]
Clica na pasta stable_diffusion_weights e veja se a pasta 800 foi criada. Ela é gerada pelo accelerate e mesmo ele validando a execução as vezes não cria a pasta por algum outro motivo

**Comment by LeonardoRJR** [comment]
O meu deu o mesmo erro, alguém conseguiu resolver?
![erro](https://user-images.githubusercontent.com/119907085/206341671-8ec59c96-0bfb-40e7-82bd-7f6a90d5b5d2.png)

**Comment by Dpbm** [comment]
Este problema, como dito pela @lorenabuzzi, é causado quando o accelerate não cria uma pasta `800` dentro de `stable_diffusion_weights/zwx`. 
Algo que pode ajudar vocês é reiniciar o runtime e rodar tudo novamente, para isso bastar ir em `Runtime > Manage Sessions > Terminate` e depois ir executando célula a célula.

Tentem isso, enquanto vou tentar averiguar o que está acontecendo.

**Comment by rayanpm** [comment]
Fiz todo o processo e agora o erro mudou.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-72-169bc3808ed1>](https://localhost:8080/#) in <module>
      5 
      6 weights_folder = OUTPUT_DIR
----> 7 folders = sorted([f for f in os.listdir(weights_folder) if f != "0"], key=lambda x: int(x))
      8 
      9 row = len(folders)

[<ipython-input-72-169bc3808ed1>](https://localhost:8080/#) in <lambda>(x)
      5 
      6 weights_folder = OUTPUT_DIR
----> 7 folders = sorted([f for f in os.listdir(weights_folder) if f != "0"], key=lambda x: int(x))
      8 
      9 row = len(folders)

ValueError: invalid literal for int() with base 10: '.ipynb_checkpoint

mais alguém aconteceu isso? Não sei o que fazer.

**Comment by daciowinchester** [comment]
Vai em ISSUE na aba closed procura por Run to generate a grid of preview images from the last saved weights. https://github.com/Dpbm/dreambooth-tutorial/issues/15 olha o tutorial do cara la resolveu meu problema

**Comment by Dpbm** [comment]
# !UPDATE

caso não funcione de uma olhada no novo tutorial, fiz o build do xformers e talvez isso possa ajudar
