### ISSUE TITLE
[ERRO] Estou tendo problema ao dar launch no dreambooth para começar a treinar a IA com meu rosto. 

### ISSUE THREAD

**Issue by cauabs** [Dpbm/dreambooth-tutorial#17]
O erro que aparece ao dar run na célula é esse:

`The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--num_cpu_threads_per_process` was set to `1` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/usr/local/lib/python3.8/dist-packages/xformers/_C.so: undefined symbol: _ZNK3c104impl13OperatorEntry20reportSignatureErrorENS0_12CppSignatureE
WARNING: /usr/local/lib/python3.8/dist-packages/xformers/_C.so: undefined symbol: _ZNK3c104impl13OperatorEntry20reportSignatureErrorENS0_12CppSignatureE
Need to compile C++ extensions to get sparse attention support. Please run python setup.py build develop
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py", line 324, in load_config
    config_file = hf_hub_download(
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 172, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: ''.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_dreambooth.py", line 822, in <module>
    main(args)
  File "train_dreambooth.py", line 448, in main
    pipeline = StableDiffusionPipeline.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/diffusers/pipeline_utils.py", line 447, in from_pretrained
    config_dict = cls.load_config(
  File "/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py", line 361, in load_config
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co/' to load this model, couldn't find it in the cached files and it looks like  is not the path to a directory containing a model_index.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth.py', '--pretrained_model_name_or_path=', '--pretrained_vae_name_or_path=stabilityai/sd-vae-ft-mse', '--output_dir=', '--revision=fp16', '--with_prior_preservation', '--prior_loss_weight=1.0', '--seed=1337', '--resolution=512', '--train_batch_size=1', '--train_text_encoder', '--mixed_precision=fp16', '--use_8bit_adam', '--gradient_accumulation_steps=1', '--learning_rate=1e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=50', '--sample_batch_size=4', '--max_train_steps=800', '--save_interval=10000', '--save_sample_prompt=cauabs', '--concepts_list=concepts_list.json']' returned non-zero exit status 1.`

**Comment by Dpbm** [comment]
Certifique-se de que o nome da sua token não possua nenhum caractere especial (como espaços, "-", ".", ",", etc.).

**Comment by cauabs** [comment]
Pior que não tem, ele tá assim desde ontem. Já testei hoje de novo com uma token diferente com nome diferente e nada de funcionar.

**Comment by daciowinchester** [comment]
Vai em ISSUE na aba closed procura por Run to generate a grid of preview images from the last saved weights. https://github.com/Dpbm/dreambooth-tutorial/issues/15 olha o tutorial do cara la resolveu meu problema

**Comment by cauabs** [comment]
Pois é, eu vi isso mas até rodando esse outro xformers não funcionou. É como se desse problema na comunicação do colab com o hugginface

**Comment by daciowinchester** [comment]
po que pena :/

**Comment by Dpbm** [comment]
# !UPDATE

Fiz o build do xformers, tente rodar com o novo tutorial
