### ISSUE TITLE
ERRO CRIAÇÃO DA PASTA 800

### ISSUE THREAD

**Issue by LeonardoRJR** [Dpbm/dreambooth-tutorial#18]
![erro](https://user-images.githubusercontent.com/119907085/206465358-d59a5288-cf1f-4a59-b4a4-6f7394ed7ada.png)
 Bom dia, está dando esse erro e acredito seja porquê não está criando a pasta 800.Alguém achou uma solução.?

**Comment by daciowinchester** [comment]
Vai em ISSUE na aba closed procura por Run to generate a grid of preview images from the last saved weights. https://github.com/Dpbm/dreambooth-tutorial/issues/15 olha o tutorial do cara la resolveu meu problema

**Comment by Dpbm** [comment]
# !UPDATE

caso não funcione de uma olhada no novo tutorial, fiz o build do xformers e talvez isso possa ajudar
