### ISSUE TITLE
Dessa vez esta dando erro em tudo

### ISSUE THREAD

**Issue by Rodrigonobrex** [Dpbm/dreambooth-tutorial#19]
Eu botei uma outra token, não repara no nome que eu botei, olha  aqui, pena que não deu pra por, eu não tenho  computador pra fazer mas enfim. Eu fiz tudo certo.
![Screenshot_20221208-150403_Chrome](https://user-images.githubusercontent.com/120036549/206530732-7c7e4de4-ea5f-4f5d-aa4c-2eedf961c0be.jpg)
![Screenshot_20221208-150407_Chrome](https://user-images.githubusercontent.com/120036549/206530747-8963c365-f1be-46de-a507-7abd041d400a.jpg)
![Screenshot_20221208-150413_Chrome](https://user-images.githubusercontent.com/120036549/206530755-23cc3815-e390-4833-94cd-d87812ecb5d7.jpg)
![Screenshot_20221208-150419_Chrome](https://user-images.githubusercontent.com/120036549/206530760-fc98a341-63e0-4d0c-9c30-914d3efb6381.jpg)

**Comment by daciowinchester** [comment]
Vai em ISSUE na aba closed procura por Run to generate a grid of preview images from the last saved weights. https://github.com/Dpbm/dreambooth-tutorial/issues/15 olha o tutorial do cara la resolveu meu problema

**Comment by Dpbm** [comment]
Durante sua execução algumas células foram traduzidas para português, como os comandos são totalmente em inglês, o notebook não vai funcionar, tente desativar o tradutor automático para essa aba do seu navegador.
Além disso, nos momentos em que você precisa colocar o nome da sua token há chaves ao redor, tente remove-los também.

Se nada disso funcionar, de uma olhada também no tutorial atualizado que está no repositório.

**Comment by Rodrigonobrex** [comment]
Obrigado  vou tentar de novo kkkk

**Comment by Rodrigonobrex** [comment]
Deu certo

**Comment by Rodrigonobrex** [comment]
@Dpbm deu certo, só mais uma pergunta tem como salva o código deixar salvo se caso eu quiser fazer mais, eu peguei algumas que eu gostei, porém deu falha ao fazer dowload, eu limpei a configuração  do app do Google Chrome.

**Comment by Dpbm** [comment]
Infelizmente o script em si não possui uma opção para salvar, mas vou deixar aqui linkado algumas issues anteriores que podem te ajudar.

#5 e #10.

**Comment by Rodrigonobrex** [comment]
@Dpbm Único jeito que eu salvei vou clicando em fui salvando no telegram

**Comment by Dpbm** [comment]
Do jeito que o script está hoje é bastante chato salvar o progresso.
Vou adicionar isso na minha lista de melhorias.

**Comment by Rodrigonobrex** [comment]
@Dpbm eu vi um vídeo de um cara aonde na parte das imagens dos cachorro ele botou o link do código da imagem por ali, só que eu fiz e gerei ali também, porém eu  o negócio ta rodando sem parar, tem como cancelar que ele rode essa parte?
![Screenshot_20221213-085304_Chrome](https://user-images.githubusercontent.com/120036549/207310869-9e429220-ec52-473b-932b-7e2cb6395701.jpg)

**Comment by Dpbm** [comment]
Geralmente o no mesmo local onde você clica para rodar, se você clicar de novo ele para a execução. Contudo se isso não funcionar, você pode ir no topo da página em `Runtime > Interrupt Execution` ou ainda `Runtime > Restart runtime`. Caso nada disso funcione, vá em `Runtime > Manage Sessions > Terminate` ou simplesmente feche a aba e abra de novo.

**Comment by Rodrigonobrex** [comment]
@Dpbm ontem gerei mais depois fui tentar fazer de novo, deu esse hoje cedo agora também, tem como excluir esse problema?
![Screenshot_20221215-074911_Chrome](https://user-images.githubusercontent.com/120036549/207840566-a4097ebf-4f29-4148-84b5-0231983e7c8a.jpg)

**Comment by Dpbm** [comment]
Como estamos usando o `Google Colab` em sua versão gratuita, temos algumas limitações com o hardware.
Já tive esse problema, para mim após algumas horas esse erro desapareceu, mas para resolver nesse momento tente esses passos:

1. Veja se não há outras abas executando o Google Colab, se tiver, feche-as;
2. Tente finalizar todas as sessões, para isso vá em `Runtime > Manage Sessions` e depois clique em `Terminate` para todas as sessões listadas;
3. Se nada disso resolver, tente esperar um tempo antes de executar novamente.
