### ISSUE TITLE
Install xformers from precompiled wheel. ERROR

### ISSUE THREAD

**Issue by ajaqueduarte** [Dpbm/dreambooth-tutorial#2]
- Estou tendo erro quando vou instalar o xformers

- Quando termina de rodar fica verde, mas com essa mensagem de erro

ERROR: xformers-0.0.14.dev0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.

- Consigo o rodar o restante ate o ponto "Run to generate a grid of preview images from the last saved weights."

IndexError                                Traceback (most recent call last)
[<ipython-input-15-169bc3808ed1>](https://iuoeouywehb-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20221129-060111-RC00_491562050#) in <module>
      8 
      9 row = len(folders)
---> 10 col = len(os.listdir(os.path.join(weights_folder, folders[0], "samples")))
     11 scale = 4
     12 fig, axes = plt.subplots(row, col, figsize=(col*scale, row*scale), gridspec_kw={'hspace': 0, 'wspace': 0})

IndexError: list index out of range

- Quando chega aqui aqui da vermelho e não deixa rodar o restante, acretido que tenha haver com o xformers que deu error

**Comment by Dpbm** [comment]
No caso da instalação do `xformers`, comecei a ter o mesmo problema, acredito que seja algo com essa versão usada pelo modelo. Mas consegui resolver rodando o seguinte comando

```bash
%pip install "git+https://github.com/facebookresearch/xformers@1d31a3a#egg=xformers"
```

Para mim isso funcionou, demorou uns `40min` a `1h` para terminar o build, mas depois disso consegui prosseguir.

---

Na parte do `Run to generate a grid of preview images from the last saved weights`, você pode acabar tendo o mesmo problema do @henriquegonc, então recomendo após você instalar o `xformers`, com o comando que lhe mostrei acima, caso continue esse erro do grid, de uma olhada [nessa issue](https://github.com/Dpbm/dreambooth-tutorial/issues/1)

**Comment by henriquegonc** [comment]
Vou testar já a solução do primeiro Issue, obrigado.

Mas acredito que vou ter esse problema do xformers também. Como executo esse comando? Onde coloco ele?

**Comment by Dpbm** [comment]
Para executar, troque essas linhas (pode ser apagando mesmo)

![xformers_problem](https://user-images.githubusercontent.com/75098594/205062065-99973236-fb88-4274-9cee-370af2b72eb9.png)

por esse comando
```bash
%pip install "git+https://github.com/facebookresearch/xformers@1d31a3a#egg=xformers"
```

**Comment by fredmpeixoto** [comment]
@Dpbm sua solução resolveu o problema, obrigado. 100% rodando.

**Comment by ajaqueduarte** [comment]
> No caso da instalação do `xformers`, comecei a ter o mesmo problema, acredito que seja algo com essa versão usada pelo modelo. Mas consegui resolver rodando o seguinte comando
> 
> ```shell
> %pip install "git+https://github.com/facebookresearch/xformers@1d31a3a#egg=xformers"
> ```
> 
> Para mim isso funcionou, demorou uns `40min` a `1h` para terminar o build, mas depois disso consegui prosseguir.
> 
> Na parte do `Run to generate a grid of preview images from the last saved weights`, você pode acabar tendo o mesmo problema do @henriquegonc, então recomendo após você instalar o `xformers`, com o comando que lhe mostrei acima, caso continue esse erro do grid, de uma olhada [nessa issue](https://github.com/Dpbm/dreambooth-tutorial/issues/1)
