### ISSUE TITLE
Colab e GPU

### ISSUE THREAD

**Issue by andremalms** [Dpbm/dreambooth-tutorial#21]
Fiz uma primeira tentativa e no meio do treinamento o colab desconectou do ambiente de execução. Depois disse: Não é possível conectar ao back-end da GPU

O que fazer nesse caso? Obrigado

**Comment by Dpbm** [comment]
Infelizmente, não sei se há uma maneira rápida de resolver isso. Recentemente tive o mesmo problema e após um dia de espera o erro sumiu.

Contudo, talvez seguindo esses passos o problema  pode ser resolvido:

1. Veja se há alguma sessão ativa, vá em `Runtime > Manage Sessions` se houver algo lá, clique em `Terminate` e tente tudo de  novo.
2. Veja também se o tipo de runtime está como `GPU`, para isso vá em `Runtime > Change Runtime Type`.

Pode ser que isso lhe ajude 😊

**Comment by EriveltonLima** [comment]
O tempo médio de espera é 12 horas para reiniciar as sessões de  uso GPU no google collab por conta google. É possível sempre usar mais de uma conta.
