### ISSUE TITLE
problema com o path do modelo

### ISSUE THREAD

**Issue by andremalms** [Dpbm/dreambooth-tutorial#22]
a instrução 12 diz:
Na seção Inference, mude a variável model_path de WEIGHTS_DIR para "stable_diffusion_weights/zwx/800"
Porém ao mudar a variável ocorre a mensagem de erro:
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like stable_diffusion_weights/zwx/800 is not the path to a directory containing a model_index.json file.Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'. site:stackoverflow.com

**Comment by andremalms** [comment]
a princípio consegui fazer funcionar com o caminho para o meu drive:
"/content/drive/MyDrive/stable_diffusion_weights/zwx/800"   
o que provavelmente significa que o path do tutorial só deva valer pra quem não está marcando o item [4] save_to_gdrive. Acredito que poderia estar no tutorial a relação de causa-efeito

**Comment by Dpbm** [comment]
Realmente, o tutorial é baseado no storage provido pela sessão do google colab, no seu caso você terá de utilizar caminhos como esse para todos os comandos.

Mas, obrigado pela ideia, assim que possível vou adicionar lá ✌️
