### ISSUE TITLE
Erro na etapa 12, na aba Inference

### ISSUE THREAD

**Issue by LuisBazacas** [Dpbm/dreambooth-tutorial#24]
Ao realizar o passo a passo, na etapa 12 estou recebendo a seguinte mensagem de erro:

![image](https://user-images.githubusercontent.com/119983796/206878689-d85adf0f-bb65-4ba0-8b43-e1c6d139531f.png)

Queria saber se você consegue me ajudar a arrumar, muito obrigado!

**Comment by efss7** [comment]
To com o mesmo problema

**Comment by EriveltonLima** [comment]
é preciso rodar o bloco "Install Requirements" Ele pega o diffusers do github do ShivamShrirao. 
![image](https://user-images.githubusercontent.com/364834/206922751-7a751279-1ac3-4ffa-818b-3d34a1c59c7a.png)

**Comment by LuisBazacas** [comment]
Após realizar esse ajuste, e de rodar a aba do Settings and run eu ainda tive algum erro na hora de rodar a aba Interference:
![image](https://user-images.githubusercontent.com/119983796/207198494-78ecc719-e769-44eb-8102-1da0e402fcba.png)

**Comment by EriveltonLima** [comment]
Está errado o "model_path". Refaça passo 14. É preciso que seja na Seção Inference, mude a variável model_path para  >>>> "stable_diffusion_weights/zwx/800"
