### ISSUE TITLE
Uma duvida com o prompt negativo

### ISSUE THREAD

**Issue by Rodrigonobrex** [Dpbm/dreambooth-tutorial#27]
É  que eu não entendi muito bem o que ele funciona.

**Comment by Dpbm** [comment]
O prompt negativo são termos que você não quer ver em suas imagens resultantes. 
Digamos que você queira criar uma imagem de um oceano, mas por algum motivo a IA está adicionando peixes na imagem, para removê-los você acrescenta o termo peixe no prompt negativo.

se você quiser entender melhor, veja [esse artigo](https://towardsdatascience.com/stable-diffusion-using-hugging-face-variations-of-stable-diffusion-56fd2ab7a265)
