### ISSUE TITLE
Erro no inference e para gerar preview das imagens

### ISSUE THREAD

**Issue by TellinhaVischi** [Dpbm/dreambooth-tutorial#28]
Estou tendo dois erros, um deles é no [8] - NameError: name 'OUTPUT_DIR' is not defined
E no [14] - OSError: We couldn't connect to 'https://huggingface.co/' to load this model, couldn't find it in the cached files and it looks like /content/drive/MyDrive/stable_diffusion_weights/zwx/800 is not the path to a directory containing a model_index.json file.
O erro do 14 já testei de duas formas, da forma que está no tutorial e na forma que está em um dos issues, mas continua apresentando o mesmo erro.
Não encontrei nenhum botão para que o modelo interaja com minha conta do HuggingFace (não sei se pode ser esse o problema)

**Comment by Dpbm** [comment]
Certifique-se de ter executado a sessão `Settings and run`. Isso pois, o primeiro erro leva ao segundo, uma vez que sem a criação da pasta `stable_diffusion_weights/zwx` não será possível configurar o HuggingFace corretamente.

![error 8](https://user-images.githubusercontent.com/75098594/212467478-816eea9a-fc95-4088-90ce-835bd85b2c0b.png)

**Comment by henriquebol** [comment]
O mesmo problema aqui. Não consegui resolver

**Comment by Dpbm** [comment]
@henriquebol a pasta `stable_diffusion_weights/zwx/800/`  foi criada?

**Comment by henriquebol** [comment]
> @henriquebol a pasta `stable_diffusion_weights/zwx/800/` foi criada?

Não, só a zwx. O código funcionava sem problemas, mas testei recentemente o mesmo código e está ocorrendo esse erro.

Já tentei com:
`%pip install -q https://github.com/ShivamShrirao/xformers-wheels/releases/download/4c06c79/xformers-0.0.15.dev0+4c06c79.d20221201-cp38-cp38-linux_x86_64.whl`,  

`!pip install https://github.com/brian6091/xformers-wheels/releases/download/0.0.15.dev0%2B4c06c79/xformers-0.0.15.dev0+4c06c79.d20221205-cp38-cp38-linux_x86_64.whl` e o 

`%pip install git+https://github.com/facebookresearch/xformers`. 


![Captura de tela de 2023-01-20 13-22-45](https://user-images.githubusercontent.com/3309893/213750718-0d8686cf-d976-4305-8435-b32d2d7607d9.png)

**Comment by Dpbm** [comment]
Tente reiniciar todo o runtime e no momento que você for instalar o xformers troque o comando que está lá por
```
%pip install -q https://github.com/Dpbm/dreambooth-tutorial/releases/download/07ba3f3/xformers-0.0.15.dev0+07ba3f3.d20221208-cp38-cp38-linux_x86_64.whl
```
