### ISSUE TITLE
accelerate: command not found

### ISSUE THREAD

**Issue by LucasLaacerda** [Dpbm/dreambooth-tutorial#3]
Ao executar o bloco 14, o mesmo é executado com sucesso no Google Colab
mas o comando em si dentro do bloco parece não ser executado.

/bin/bash: accelerate: command not found

![Screen Shot 2022-12-01 at 16 51 22](https://user-images.githubusercontent.com/51750552/205146479-e45fa8ac-01ed-4f36-ac8e-cf74e3365773.png)

E consequentimente tive os problemas comuns relatado no Readme, mesmo fazendo as devidas alterações sugeridas:

![Screen Shot 2022-12-01 at 16 52 22](https://user-images.githubusercontent.com/51750552/205146650-c9f3e8a4-1fb8-42b2-9ca2-15f36503a4e4.png)

**Comment by LucasLaacerda** [comment]
Obs: Todas etapas anteriores rodaram com sucesso, inclusive o Install do xformers

**Comment by Dpbm** [comment]
Tente executar esses comandos novamente

```bash
!wget -q https://github.com/ShivamShrirao/diffusers/raw/main/examples/dreambooth/train_dreambooth.py
!wget -q https://github.com/ShivamShrirao/diffusers/raw/main/scripts/convert_diffusers_to_original_stable_diffusion.py
%pip install -qq git+https://github.com/ShivamShrirao/diffusers
%pip install -q -U --pre triton
%pip install -q accelerate==0.12.0 transformers ftfy bitsandbytes gradio natsort
```
e depois rode o bloco 14

se o problema continuar, clique no botão `+ Code` 

![new_code_block](https://user-images.githubusercontent.com/75098594/205147825-b1cc8ebc-04b7-4c91-b36b-88506072d961.png)

e depois coloque o seguinte comando

```
!which accelerate
```

![location](https://user-images.githubusercontent.com/75098594/205148095-7b223293-033a-4d6d-b41f-e92f2419a2e3.png)

se retornar algo, copie o que retornou e substitua o `accelerate` do bloco 14 por esse retorno

**Comment by LucasLaacerda** [comment]
Sucesso Alexandre, rodar o wget e o install novamente resolveu meu problema
