### ISSUE TITLE
Problema ao criar pasta

### ISSUE THREAD

**Issue by rafaorsi** [Dpbm/dreambooth-tutorial#30]
Olá pessoal, eu não manjo nada de códigos mas usava o tutorial antigo sem problemas e usei ontem inclusive quando encontrei o erro que descreverei. Muito obrigado por tudo! Esse novo formato está bem legal, porém não estou conseguindo rodar o passo 2. Dou a permissão para acessar meu drive, mas recebo erro abaixo, vou colar o print pra deixar mais claro.

![erro1](https://user-images.githubusercontent.com/126166878/220904542-2a498f1a-7e59-4e6b-b9f4-ab3bde37e610.PNG)

**Comment by Dpbm** [comment]
olá @rafaorsi, verifique se na barra lateral, na `aba files`, do seu google colab há uma pasta com o nome `drive` e dentro dela uma com nome `MyDrive`

![desse jeito](https://user-images.githubusercontent.com/75098594/220928681-e2444781-def1-4298-93ec-2f00ba1b0f9c.png)

Se houver, tente rodar essa seção novamente. Senão, verifique se tudo ocorreu bem ao aceitar o acesso ao Google Drive.

Se nada disso funcionar, tente reiniciar o ambiente indo em: `Runtime > Manage Sessions > Terminate`, após isso, tente recomeçar o tutorial.

**Comment by rafaorsi** [comment]
tem a pasta sim, drive / my drive, tinha notado q ela aparece depois q eu aceito a permissão do drive, tentei rodar algumas vezes e não vai, continua dando o mesmo erro. (inclusive a pasta do stable está lá também, será que é melhor eu deletar pra ele criar uma nova?)

tentei terminar a sessão e começar de novo, o primeiro passo roda normal, no 2 preencho o nome e o token do hugging face (mesmo que usava no tutorial antigo, precisa criar um novo pra esse?), aí pede a permissão do drive, eu aceito e dá o mesmo erro.

**Comment by Dpbm** [comment]
Percebi que o erro estava no código. Ao desenvolver utilizei o comando errado para criar caminhos de pastas.
Acredito que agora o problema está resolvido. Teste com esse novo script e veja se está funcionando para você.

[![DreamBooth Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Dpbm/dreambooth-tutorial/blob/main/notebooks/dreambooth.ipynb)

Muito obrigado por relatar o problema 😊

**Comment by rafaorsi** [comment]
notei sua edição e ajustei aqui também, passou a funcionar!!! vou testar o resto e aviso qualquer coisa :), valeu!!!
