### ISSUE TITLE
Resultados em qualidade baixa entre versões

### ISSUE THREAD

**Issue by rafaorsi** [Dpbm/dreambooth-tutorial#32]
Olha eu aqui de novo :)

Parabéns pela nova interface, ficou bem mais prática que a versão anterior, porém os resultados estão muito diferentes para mim. Houve alguma mudança na AI? Vou por alguns exemplos que fiz no antes e depois, exatamente as mesmas selfies e prompt para comparação mesmo! Tenho a impressão que algumas palavras não estão sendo lidas, ou ignoradas na nova versão. Vamos lá!

**VERSÃO ANTERIOR:** ficaram muito parecidas comigo
![tmpbegezgrm](https://user-images.githubusercontent.com/126166878/220968174-abb16664-c531-4777-9988-8e3ac4e8dccf.png)
![tmpumse64f4](https://user-images.githubusercontent.com/126166878/220968178-59c2116f-fb11-45c2-800c-864b7bba94f5.png)
![tmpuwcr8iru](https://user-images.githubusercontent.com/126166878/220968183-8cdb0bdc-956d-4cea-93f7-557ff7148d9e.png)

**VERSÃO ATUAL:** não lembram a mim nem de longe, inclusive botou um óculos q eu não usei em nenhuma das selfies, fiz umas 50 imagens e nada.
![2caaaeed-3df7-4156-adc1-fce4adee6083](https://user-images.githubusercontent.com/126166878/220968677-0dc14136-48a3-4d28-bca4-2c52edc2e90c.png)
![5a246571-8d83-49b1-8b1e-3d32547a1b17](https://user-images.githubusercontent.com/126166878/220968682-2543e2fe-606f-4323-a6f8-ead72479eb44.png)
![9f16e58e-ab28-4152-b256-aa1cb9e9dd04](https://user-images.githubusercontent.com/126166878/220968683-8803c63a-7b6c-40a0-80dc-71b546aef6b7.png)
![d994bb22-3a64-4647-9fe0-8b1ec8cd5ed9](https://user-images.githubusercontent.com/126166878/220968689-db15499c-3f87-49b8-901e-0f2b58f2eb44.png)
![f5c7f2d8-b408-4a7f-aab9-e9750b709a76](https://user-images.githubusercontent.com/126166878/220968692-39757e09-e387-44d7-9225-0c006733e909.png)

prompt usado: `portrait of rafa as a viking king, long blond hair, long beard, blue eyes, sharp focus, highly detailed, canon 5d, 50mm, 8k,`

**Comment by Dpbm** [comment]
Acredito que o problema seja causado por versões anteriores do `xformers`. Fiz esse teste, de uma olhada se essa versão lhe traz resultados melhores


[![DreamBooth Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Dpbm/dreambooth-tutorial/blob/newXformers/notebooks/dreambooth.ipynb)

**Comment by rafaorsi** [comment]
deu esse erro quando tentei ligar a gpu
![erro2](https://user-images.githubusercontent.com/126166878/221013838-3c7d7443-dc6f-4815-b141-57057bb6c11a.PNG)

**Comment by Dpbm** [comment]
Esse erro geralmente acontece ao utilizar, sequencialmente, várias sessões com GPU. Essa é uma limitação do plano grátis do Colab. 
Tente novamente terminar as sessões ou senão tente rodar mais tarde.

**Comment by rafaorsi** [comment]
só usei na hora q criei o post, e depois quando criei o comentário, não fiquei utilizando várias sessões, mas fechei no gerenciamento agora pra aguardar mais tarde, vamos ver

**Comment by rafaorsi** [comment]
o mesmo erro persiste, há outro motivo para isso?

**Comment by Dpbm** [comment]
Acredito que não. Diversas vezes, quando estava testando, tive que ficar algumas boas horas sem utilizar o colab.
 
Creio que amanhã, o google colab já disponibilizará à você mais uma máquina com GPU.

Caso você queira testar ainda hoje, utilizar outra conta do google pode ajudar.

**Comment by rafaorsi** [comment]
Consegui testar hoje, ficou bem melhor. 


![5478d154-f219-4de4-b845-4a2859be53b3](https://user-images.githubusercontent.com/126166878/221208936-c5fb44d4-e0b1-422b-9e7e-7fc3b880a4a3.png)
![77028001-eeae-40eb-a4ba-cd5d0b017b86](https://user-images.githubusercontent.com/126166878/221208940-172d0447-9ab8-4577-8a0b-4a952320f6c1.png)
![a680fcf1-4a48-4ead-b55b-043e93592b9c](https://user-images.githubusercontent.com/126166878/221208943-9c5294ef-1735-4b49-9434-e31f4d2477b9.png)
![1c45104f-bac5-4fdd-adff-430153639bc8](https://user-images.githubusercontent.com/126166878/221208925-b626ec49-b0d7-4228-95cd-e1dcf5ba502e.png)
![6fc51a09-7537-4832-a6c9-eb4cbaaf4014](https://user-images.githubusercontent.com/126166878/221208932-a6187e5a-99f0-4c3d-96af-411fe2ee5245.png)

**Comment by Dpbm** [comment]
Fiz o merge com o novo xformers setado. 
Acredito que as imagens agora terão uma qualidade nesse nível. 

Obrigado por ajudar 😊
