### ISSUE TITLE
RuntimeError - CUDA out of memory

### ISSUE THREAD

**Issue by vtrx1992** [Dpbm/dreambooth-tutorial#4]
Eu consegui gerar algumas imagens, mas depos apareceu isso, o que é esse erro?

![erro](https://user-images.githubusercontent.com/108581414/205156932-4528ac97-d59b-4fc0-a449-da216777cc90.jpg)

**Comment by MatheussAlves** [comment]
Falta de memoria de video, la no ultimo codigo tem uma opção de limpar a memoria
