### ISSUE TITLE
salvar imagens

### ISSUE THREAD

**Issue by samalvarenga** [Dpbm/dreambooth-tutorial#5]
Olá ! consegui seguir todo o fluxo e gerei as imagens. Porém, não consigo salvá-las. Clico com o direito do mouse > salvar imagem como... ele salva a imagem como um .pgn de 1kb... não consigo abrir...

Como faz pra salvar as imagens geradas:?

**Comment by brcappio** [comment]
Cara eu consegui fazer de um jeito não muito otimizado mas funciona

Quando você clica pra gerar as imagens elas ficam salvas em uma pasta dentro do colab chamada tmp, então nosso objetivo vai ser baixar essa pasta inteira pra não ter que baixar as imagens uma por uma.

Então quando quiser parar de gerar as imagens e salvar todas que você fez você vai fazer o seguinte: 

1 - Primeiro vamos abrir o explorador de arquivos ali no canto e depois clicar pra subir um nível.
![image](https://user-images.githubusercontent.com/92182943/205223935-6668d3bf-caf4-417c-8be3-a9ce7f24c8e4.png)


2 - Agora vamos parar a célula que gera as imagens (eu utilizei o Gradio UI, fica em baixo da onde vc coloca o prompt)
![image](https://user-images.githubusercontent.com/92182943/205222004-28fa5bdb-c2d6-48de-a682-4ee5f2c61229.png)


3 - Depois que a célula tiver parado você vai montar o seu google drive dentro do colab.
Pra fazer isso vamos clicar no ícone do drive), depois disso uma nova célula será criada.
![image](https://user-images.githubusercontent.com/92182943/205224409-e3b998ba-e7af-40ca-83c0-91b83e23554d.png)


Agora vamos rodar ela.
![image](https://user-images.githubusercontent.com/92182943/205222657-87417490-6b14-40d7-a09e-159930903b44.png)

Depois que clicar pra rodar vai aparecer uma mensagem pedindo pra você autorizar a conexão com o drive, só clicar em permitir e escolher qual conta do drive você quer usar pra salvar suas imagens.


4 - Agora com o nosso drive dentro do colab nós vamos jogar a pasta tmp que contém as imagens que geramos pra dentro do nosso drive.

![image](https://user-images.githubusercontent.com/92182943/205224536-3cc0ac41-7bb7-4c15-a313-24f938d35ae1.png)

Vamos mover essa pasta para o nosso drive

![image](https://user-images.githubusercontent.com/92182943/205224613-b8923bc0-a0bd-42bc-a7ff-99eaafc8f2d4.png)

(Note que existe a pasta 'tmp' e DENTRO dela existe 'tmp......' (no meu caso 'tmpejfmg....') e é nela que suas imagens estarão)


Feito isso você pode abrir o seu drive e a pasta com todas as imagens vai estar lá, ai é só clicar pra baixar a pasta que o drive vai zipar tudo e fazer o download.
