### ISSUE TITLE
parte 51

### ISSUE THREAD

**Issue by samuraidasflores** [Dpbm/dreambooth-tutorial#6]
a parte de número 51 não funciona e exibe essa mensagem

(ps: sou 100% leigo em programação, cheguei ao tutorial por um fio/thread no twitter):

---------------------------------------------------------------------------
HFValidationError                         Traceback (most recent call last)
[/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py](https://localhost:8080/#) in load_config(cls, pretrained_model_name_or_path, return_unused_kwargs, **kwargs)
    323                 # Load from URL or cache if already cached
--> 324                 config_file = hf_hub_download(
    325                     pretrained_model_name_or_path,

4 frames
HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'stable_diffusion_weights/zwx/800'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
[/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py](https://localhost:8080/#) in load_config(cls, pretrained_model_name_or_path, return_unused_kwargs, **kwargs)
    359                 )
    360             except ValueError:
--> 361                 raise EnvironmentError(
    362                     f"We couldn't connect to '{HUGGINGFACE_CO_RESOLVE_ENDPOINT}' to load this model, couldn't find it"
    363                     f" in the cached files and it looks like {pretrained_model_name_or_path} is not the path to a"

OSError: We couldn't connect to 'https://huggingface.co/' to load this model, couldn't find it in the cached files and it looks like stable_diffusion_weights/zwx/800 is not the path to a directory containing a model_index.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.

**Comment by Dpbm** [comment]
Como expresso na última linha do erro `Checkout your internet connection or see how to run the library in offline mode at `  pode ser que sua conexão com o Google colab não foi estabelecida.
Observe se no canto superior direito você possui algo semelhante a isso:


![connected](https://user-images.githubusercontent.com/75098594/205283322-9901b8f7-a86a-430d-a88f-0c83d6fdc36c.png)

Se estiver tudo certo nessa parte,  aconselho abrir um novo arquivo clicando aqui  [![DreamBooth Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ShivamShrirao/diffusers/blob/main/examples/dreambooth/DreamBooth_Stable_Diffusion.ipynb) e após isso, siga os passos do tutorial a risca, lembrando sempre que:

Aqui você adicionar a token, ou seja você entra [aqui](https://huggingface.co/settings/tokens) clica no botão de copiar, cola no campo mostrado na imagem e clica em rodar 

![token](https://user-images.githubusercontent.com/75098594/205284383-7b0bd9d9-1460-4385-aef6-b3ac6529f97b.png)

Já nesses dois lugares você vai colocar o nome que você adicionou na hora de criar a token no [HuggingFace](https://huggingface.co/settings/tokens)

![folders](https://user-images.githubusercontent.com/75098594/205284711-6a081959-107e-48a0-b024-712338e18c5b.png)

![accelerate](https://user-images.githubusercontent.com/75098594/205284728-3a797d7e-91ec-4ee5-9fb9-b0d5d37d2962.png)

`Obs: recomendo nomear a token com um nome simples, tipo eu, avatar, pessoa, etc., evite nomes muito compridos ou com espaços`

--- 

Ser por algum acaso o erro ainda continuar, nos avise por aqui 😊

**Comment by gstavomota** [comment]
Aconteceu o mesmo erro comigo
Todos os outros passos funcionaram tranquilo

![image](https://user-images.githubusercontent.com/61586814/205301569-9a273cae-9534-4676-ad7d-6dbfece4aeed.png)

**Comment by Dpbm** [comment]
> Aconteceu o mesmo erro comigo Todos os outros passos funcionaram tranquilo
> 
> ![image](https://user-images.githubusercontent.com/61586814/205301569-9a273cae-9534-4676-ad7d-6dbfece4aeed.png)

Pelo visto o script não gerou a pasta `stable_diffusion_weights`. Os outros códigos executados deram algum erro?

**Comment by gstavomota** [comment]
> > Aconteceu o mesmo erro comigo Todos os outros passos funcionaram tranquilo
> > ![image](https://user-images.githubusercontent.com/61586814/205301569-9a273cae-9534-4676-ad7d-6dbfece4aeed.png)
> 
> Pelo visto o script não gerou a pasta `stable_diffusion_weights`. Os outros códigos executados deram algum erro?

Não... todos rodaram certinho

**Comment by Dpbm** [comment]
Testei um pouco do código e a seção `Settings and run` é responsável pela criação dessa pasta, tente rodá-la novamente e verifique se nos arquivos ao lado a pasta é criada

**Comment by gstavomota** [comment]
> Testei um pouco do código e a seção `Settings and run` é responsável pela criação dessa pasta, tente rodá-la novamente e verifique se nos arquivos ao lado a pasta é criada

Funcionou!!
![image](https://user-images.githubusercontent.com/61586814/205389649-d22f7b22-e2b8-4d52-b4e6-cfad54c314dd.png)
eu tinha selecionado essa opção de "save_to_gdrive", depois que desmarquei e rodei novamente funcionou certinho
