### ISSUE TITLE
sessão 12

### ISSUE THREAD

**Issue by pazetto** [Dpbm/dreambooth-tutorial#7]
Não estou certo de que estou fazendo a coisa correta, porém até aqui tem ido tudo certo.
Na sessão 12, quando eu vou pra rodar a célula ele me dá o seguinte erro:

![image](https://user-images.githubusercontent.com/16917576/205185770-c2babd4d-c222-4c79-9b83-1e52c033f0c3.png)

O caminho ali em "zwx" eu devo mudar também ou não? Porque eu mudei onde foi falado pra mudar, mas não nesse trecho que não foi especificado.
Valeu!

**Comment by LucasLaacerda** [comment]
O path é esse mesmo, recebi esse erro quando meu notebook ficou sem GPU disponível pra usar.
Roda o primeiro bloco, para conferir se seu notebook esta usando a GPU ou nao

**Comment by Dpbm** [comment]
Este problema está relacionado com o pacote `diffusers` que não foi encontrado. 

Clique em `+ Code`, cole o seguinte comando e o execute

```bash
!pip list | grep diffusers
``` 

Caso o comando não retornar nada rode

```bash
%pip install -qq git+https://github.com/ShivamShrirao/diffusers
```

**Comment by deathyper** [comment]
Estou tendo um erro na mesma parte, linhas 324 e 361. fiz tudo de acordo, mas o erro continua, como sou bem nova nisso, nao sei identificar o que esta errado

![image](https://user-images.githubusercontent.com/19209616/205417072-24c57e7b-0c13-4eea-9025-25b13836e752.png)

**Comment by EriveltonLima** [comment]
Para resolver o problema do module diffusers tem que rodar o "install requirements" 
![image](https://user-images.githubusercontent.com/364834/205464631-1f54dbd8-f048-421f-9fd2-016e51af8d57.png)

**Comment by deathyper** [comment]
Olá! Eu rodei tudo isso antes de dar o problema. Como não entendo nada de programação, acabei alterando o max steps de 800 pra 1600, so q isso parece que me deu um monte de erros em várias sessões, pois o guia é padrão e quando eu altero algo muitas coisas no guia tb mudam. Acabei iniciando tudo de novo, segui o padrão do guia e funcionou. Mas fiquei muito curiosa sobre aumentar os steps no training.

**Comment by EriveltonLima** [comment]
@deathyper  O que acontece muitas vezes é você aumentar o número dos steps e ele ficar fora do escopo do collab e rodar muito mais memoria do que está disponivel na maquina. único resultado é Crashar. O collab foi construido para ser um modelo básico de treinamento mas continue estudando e avaliando outras possibilidades. Lembrando que todo o treinamento do modelo é feito em servidor google.

Você pode ler mais aqui : https://techpp.com/2022/10/10/how-to-train-stable-diffusion-ai-dreambooth/

**Comment by deathyper** [comment]
Interessante! Obrigada pela explicação, vou ler o link e tentar entender melhor o que posso ou não alterar e se devo.
