### ISSUE TITLE
Não é possível conectar ao back-end da GPU

### ISSUE THREAD

**Issue by brurebellato** [Dpbm/dreambooth-tutorial#8]
Hoje começou a aparecer esse erro, e não estou sabendo se tem como solucionar ele.

**Comment by Dpbm** [comment]
Dei uma pesquisada e encontrei [isso no StackOverflow](https://stackoverflow.com/questions/48508145/google-colaboratory-no-backend-with-gpu-available)

**Comment by brurebellato** [comment]
pelo que vi a configuração está correta, a mensagem que da abaixo do erro é a seguinte:
_Atualmente, não é possível conectar a uma GPU devido aos limites de uso do Colab.
Para ter mais acesso a GPUs, compre unidades de computação do Colab com [Pay As You Go]_

**Comment by Dpbm** [comment]
bem, o Google Cola na versão gratuita tem mesmo algumas limitações de hardware, então talvez se você reiniciar indo em `Runtime > Restart Runtime` pode ajudar. 
Se isso não resolver, talvez abrindo outro colab ajude, para facilitar vou deixar o botão para abrir logo abaixo

[![DreamBooth Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ShivamShrirao/diffusers/blob/main/examples/dreambooth/DreamBooth_Stable_Diffusion.ipynb)

**Comment by brurebellato** [comment]
É, nada funciona, mas vi que pode ser que 'dando um tempo' , ele pode voltar a funcionar posteriormente. Veremos.
Obrigada pela ajuda :)

**Comment by EriveltonLima** [comment]
@brurebellato Você pode tbm abrir em uma outra conta google para burlar o limite de cool-down 8 horas colab por conta.
