### ISSUE TITLE
Erro - Inference 

### ISSUE THREAD

**Issue by joaogabriel-dev** [Dpbm/dreambooth-tutorial#9]
![problema](https://user-images.githubusercontent.com/111209734/205355533-6d31ee89-7592-4e32-b72b-341a5e3fa552.png)

Estou com erro nessa parte do processo, coloquei "" em stable_diffusion_weights/zwx - como também utilizei de outros artifícios que estão em "Erro no preview das imagens e erro no prompt", que infelizmente não resolveram. Alguém poderia me ajudar?

**Comment by Dpbm** [comment]
mude o model_path para `"stable_diffusion_weights/zwx/800"` (obs: use as aspas também)

**Comment by joaogabriel-dev** [comment]
Eu já havia adicionado "" anteriormente, testei com e sem aspas, mas não alterou no resultado da mensagem

**Comment by Dpbm** [comment]
nos arquivos, há uma pasta chamada `stable_diffusion_weights` ?

**Comment by joaogabriel-dev** [comment]
Não, tentei novamente com aspas e foi isso que apareceu 
![Uploading Screenshot_1.png…]()

**Comment by joaogabriel-dev** [comment]
Não, ñ tem nenhuma pasta com esse nome. Rodei novamente com aspas e foi esse erro que apareceu 
![Screenshot_1](https://user-images.githubusercontent.com/111209734/205359956-c4e9778c-71ba-4ca5-a054-0567e71d69aa.png)

**Comment by Dpbm** [comment]
Você autorizou o Modelo no HuggingFace? [esse link](https://huggingface.co/runwayml/stable-diffusion-v1-5)

**Comment by joaogabriel-dev** [comment]
Sim, autorizei, foi meu primeiro passo

**Comment by Dpbm** [comment]
ok, seu problema é o mesmo [dessa issue](https://github.com/Dpbm/dreambooth-tutorial/issues/6#issuecomment-1335446897), passe lá e teste o que está escrito.
Enquanto isso vou tentar averiguar o que está acontecendo 😊

Acredito que este problema esteja atrelado à criação da pasta `stable_diffusion_weights`
